---
- name: debug
  debug: msg="{{ hostvars[groups['rke2_servers'].0]['inventory_hostname'] }}"

- name: Add IP address of server hosts to all hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_host }} {{item}} {{ cluster_name }}"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.rke2_servers }}"